FROM rust:latest

RUN USER=root

EXPOSE 3000/tcp
EXPOSE 5432/tcp

COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock

COPY ./src ./src

RUN cargo build --bin jwt --release

COPY ./settings.toml ./settings.toml

CMD ["./target/release/jwt"]